services:
  redis:
    command: ["redis-server", "--appendonly", "no", "--save", ""]

  simulator:
    environment:
      SIMULATOR_CONFIG_PATH: config/simulator.loadtest.10k.yaml
    restart: unless-stopped

  processor:
    environment:
      PROCESSOR_CONFIG_PATH: config/processor.loadtest.10k.yaml
    restart: unless-stopped
