services:
  simulator:
    environment:
      SIMULATOR_CONFIG_PATH: config/simulator.loadtest.100k.yaml
    restart: unless-stopped

  simulator-b:
    environment:
      SIMULATOR_CONFIG_PATH: config/simulator.loadtest.100k.yaml
    restart: unless-stopped

  processor:
    environment:
      PROCESSOR_CONFIG_PATH: config/processor.loadtest.100k.yaml
    restart: unless-stopped

  processor-b:
    environment:
      PROCESSOR_CONFIG_PATH: config/processor.loadtest.100k.yaml
    restart: unless-stopped

  processor-c:
    environment:
      PROCESSOR_CONFIG_PATH: config/processor.loadtest.100k.yaml
    restart: unless-stopped

  processor-d:
    environment:
      PROCESSOR_CONFIG_PATH: config/processor.loadtest.100k.yaml
    restart: unless-stopped
