"""Simulator-specific metric names and helpers."""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Any, Deque

from src.common.metrics import InMemoryMetricRegistry, metrics as shared_metrics
from src.common.prometheus import OptionalPrometheusRegistry


COUNTER_EVENTS_GENERATED_TOTAL = "events_generated_total"
COUNTER_EVENTS_GENERATED_BY_TYPE = "events_generated_by_type"
COUNTER_FAULT_EVENTS_GENERATED = "fault_events_generated_total"
COUNTER_DUPLICATES_INJECTED = "duplicates_injected_total"
COUNTER_OUT_OF_ORDER_INJECTED = "out_of_order_injected_total"
COUNTER_TOO_LATE_INJECTED = "too_late_injected_total"
COUNTER_PRODUCE_FAILURES = "produce_failures_total"
COUNTER_SESSION_START_BLOCKED_TICKS = "session_start_blocked_ticks_total"

GAUGE_TARGET_EPS = "target_eps"
GAUGE_ACTIVE_SESSIONS = "active_sessions"
GAUGE_ACTUAL_EPS = "actual_generated_eps"
GAUGE_ADMISSION_SCALE = "admission_scale"
GAUGE_SESSION_START_PROBABILITY_EFFECTIVE = "session_start_probability_effective"
GAUGE_SESSION_START_CAP_EFFECTIVE = "session_start_cap_effective"


@dataclass(slots=True)
class EmissionPoint:
    timestamp_monotonic: float
    count: int


class SimulatorMetrics:
    def __init__(
        self,
        registry: InMemoryMetricRegistry | None = None,
        *,
        prometheus: OptionalPrometheusRegistry | None = None,
        eps_window_seconds: float = 30.0,
    ) -> None:
        self._registry = registry or shared_metrics
        self._eps_window_seconds = max(1.0, eps_window_seconds)
        self._emissions: Deque[EmissionPoint] = deque()
        self._prometheus = prometheus

        self._prom_events_generated_total = None
        self._prom_events_generated_by_type = None
        self._prom_fault_events_generated = None
        self._prom_duplicates_injected = None
        self._prom_out_of_order_injected = None
        self._prom_too_late_injected = None
        self._prom_produce_failures = None
        self._prom_session_start_blocked_ticks = None
        self._prom_target_eps = None
        self._prom_actual_eps = None
        self._prom_active_sessions = None
        self._prom_admission_scale = None
        self._prom_session_start_probability_effective = None
        self._prom_session_start_cap_effective = None

        if prometheus is not None and prometheus.enabled:
            self._prom_events_generated_total = prometheus.counter(
                COUNTER_EVENTS_GENERATED_TOTAL,
                "Total number of events generated by simulator",
            )
            self._prom_events_generated_by_type = prometheus.counter(
                COUNTER_EVENTS_GENERATED_BY_TYPE,
                "Generated events by event_type",
                labelnames=("event_type",),
            )
            self._prom_fault_events_generated = prometheus.counter(
                COUNTER_FAULT_EVENTS_GENERATED,
                "Total FAULT_ALERT events generated",
            )
            self._prom_duplicates_injected = prometheus.counter(
                COUNTER_DUPLICATES_INJECTED,
                "Total duplicate events injected by simulator",
            )
            self._prom_out_of_order_injected = prometheus.counter(
                COUNTER_OUT_OF_ORDER_INJECTED,
                "Total out-of-order events injected by simulator",
            )
            self._prom_too_late_injected = prometheus.counter(
                COUNTER_TOO_LATE_INJECTED,
                "Total too-late events injected by simulator",
            )
            self._prom_produce_failures = prometheus.counter(
                COUNTER_PRODUCE_FAILURES,
                "Total simulator publish failures",
            )
            self._prom_session_start_blocked_ticks = prometheus.counter(
                COUNTER_SESSION_START_BLOCKED_TICKS,
                "Total simulator ticks where session starts were blocked due to overshoot",
            )
            self._prom_target_eps = prometheus.gauge(
                GAUGE_TARGET_EPS,
                "Current simulator target events-per-second",
            )
            self._prom_actual_eps = prometheus.gauge(
                GAUGE_ACTUAL_EPS,
                "Observed simulator generated events-per-second over sliding window",
            )
            self._prom_active_sessions = prometheus.gauge(
                GAUGE_ACTIVE_SESSIONS,
                "Current active sessions in simulator network state",
            )
            self._prom_admission_scale = prometheus.gauge(
                GAUGE_ADMISSION_SCALE,
                "Current EPS admission scale factor",
            )
            self._prom_session_start_probability_effective = prometheus.gauge(
                GAUGE_SESSION_START_PROBABILITY_EFFECTIVE,
                "Current effective session-start probability",
            )
            self._prom_session_start_cap_effective = prometheus.gauge(
                GAUGE_SESSION_START_CAP_EFFECTIVE,
                "Current effective per-tick session-start cap",
            )

    def increment_generated(self, event_type: str, amount: int = 1) -> None:
        self._registry.increment(COUNTER_EVENTS_GENERATED_TOTAL, amount)
        metric_name = f"{COUNTER_EVENTS_GENERATED_BY_TYPE}_{event_type.lower()}_total"
        self._registry.increment(metric_name, amount)
        _inc_counter(self._prom_events_generated_total, amount)
        if self._prom_events_generated_by_type is not None:
            self._prom_events_generated_by_type.labels(event_type=event_type).inc(amount)

    def increment_fault_events(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_FAULT_EVENTS_GENERATED, amount)
        _inc_counter(self._prom_fault_events_generated, amount)

    def increment_duplicates(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_DUPLICATES_INJECTED, amount)
        _inc_counter(self._prom_duplicates_injected, amount)

    def increment_out_of_order(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_OUT_OF_ORDER_INJECTED, amount)
        _inc_counter(self._prom_out_of_order_injected, amount)

    def increment_too_late(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_TOO_LATE_INJECTED, amount)
        _inc_counter(self._prom_too_late_injected, amount)

    def increment_produce_failures(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_PRODUCE_FAILURES, amount)
        _inc_counter(self._prom_produce_failures, amount)

    def increment_session_start_blocked_ticks(self, amount: int = 1) -> None:
        self._registry.increment(COUNTER_SESSION_START_BLOCKED_TICKS, amount)
        _inc_counter(self._prom_session_start_blocked_ticks, amount)

    def set_target_eps(self, eps: float) -> None:
        bounded = max(0.0, float(eps))
        self._registry.set_gauge(GAUGE_TARGET_EPS, bounded)
        if self._prom_target_eps is not None:
            self._prom_target_eps.set(bounded)

    def set_active_sessions(self, count: int) -> None:
        bounded = float(max(0, count))
        self._registry.set_gauge(GAUGE_ACTIVE_SESSIONS, bounded)
        if self._prom_active_sessions is not None:
            self._prom_active_sessions.set(bounded)

    def set_admission_scale(self, scale: float) -> None:
        bounded = max(0.0, float(scale))
        self._registry.set_gauge(GAUGE_ADMISSION_SCALE, bounded)
        if self._prom_admission_scale is not None:
            self._prom_admission_scale.set(bounded)

    def set_session_start_probability_effective(self, value: float) -> None:
        bounded = max(0.0, float(value))
        self._registry.set_gauge(GAUGE_SESSION_START_PROBABILITY_EFFECTIVE, bounded)
        if self._prom_session_start_probability_effective is not None:
            self._prom_session_start_probability_effective.set(bounded)

    def set_session_start_cap_effective(self, cap: int) -> None:
        bounded = float(max(0, int(cap)))
        self._registry.set_gauge(GAUGE_SESSION_START_CAP_EFFECTIVE, bounded)
        if self._prom_session_start_cap_effective is not None:
            self._prom_session_start_cap_effective.set(bounded)

    def observe_emitted(self, count: int, now_monotonic: float) -> float:
        self._emissions.append(EmissionPoint(timestamp_monotonic=now_monotonic, count=max(0, count)))
        self._trim(now_monotonic)
        eps = self.current_eps(now_monotonic)
        self._registry.set_gauge(GAUGE_ACTUAL_EPS, eps)
        if self._prom_actual_eps is not None:
            self._prom_actual_eps.set(eps)
        return eps

    def current_eps(self, now_monotonic: float) -> float:
        self._trim(now_monotonic)
        if not self._emissions:
            return 0.0

        total_count = sum(item.count for item in self._emissions)
        elapsed = max(
            self._eps_window_seconds,
            now_monotonic - self._emissions[0].timestamp_monotonic,
        )
        return total_count / elapsed

    def snapshot(self) -> dict[str, dict[str, float | int]]:
        snap = self._registry.snapshot()
        return {
            "counters": dict(snap.counters),
            "gauges": dict(snap.gauges),
        }

    def _trim(self, now_monotonic: float) -> None:
        lower_bound = now_monotonic - self._eps_window_seconds
        while self._emissions and self._emissions[0].timestamp_monotonic < lower_bound:
            self._emissions.popleft()


def _inc_counter(counter: Any | None, amount: int) -> None:
    if counter is None:
        return
    counter.inc(amount)
